### ISSUE TITLE
Unable to checkout working tree

### ISSUE THREAD

**Issue by ferasterkawi** [jonDel/emg_mc#6]
Hi:

An occurred error with: git clone https://github.com/jonDel/emg_mc.git

C:\Users\feras\emg_mc>git clone https://github.com/jonDel/emg_mc.git
Cloning into 'emg_mc'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
Receiving objects: 100% (635/635), 445.28 MiB | 114.00 KiB/s, done.
remote: Total 635 (delta 2), reused 0 (delta 0), pack-reused 629
Resolving deltas: 100% (208/208), done.
error: invalid path 'results/history/db1/ts20/subject:10_history.pickle'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by jonDel** [comment]
Hi, I just checked it out and it seems ok:
```linux
$ git clone https://github.com/jonDel/emg_mc.git todel                                                            
Cloning into 'todel'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 635 (delta 2), reused 0 (delta 0), pack-reused 629
Receiving objects: 100% (635/635), 445.28 MiB | 705.00 KiB/s, done.
Resolving deltas: 100% (208/208), done.
Checking out files: 100% (193/193), done.
```
It can be something related to available space in your drive. Take a look at this: https://stackoverflow.com/questions/22041752/github-clone-succeeded-but-checkout-failed/22044854
